# Generated by Django 6.0.7 on 2026-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_galleryimage_image_alter_instructor_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g., "8", "20", "1"', max_length=50)),
                ('title', models.CharField(help_text='e.g., "Belt Ranks Taught"', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the display order')),
                ('is_active', models.BooleanField(default=True, help_text='Allows hiding/showing this statistic')),
            ],
            options={
                'verbose_name': 'Academy Statistic',
                'verbose_name_plural': 'Academy Statistics',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
